### ISSUE TITLE
Request for Fabric Loader 0.16.0 - 1.21 Compatibility

### ISSUE THREAD

**Issue by MrCookie112** [lukasabbe/Paste-book-text#2]
Hello,

First of all, I'd like to thank you for your superb mod. However, I've noticed that the mod currently only works with the latest version of Fabric Loader and that many other mods are not compatible with it. This makes it difficult for me to take advantage of your mod.

Would it be possible to add support for Fabric Loader 0.16.0-1.21? This would be much appreciated by users like me who depend on an older version for the compatibility of their other mods.

**Comment by lukasabbe** [comment]
Sure, I did not even know some mods can't run with newer fabric loaders. I only thought it went the other way.
I can of course make a version, but what mod is not working with the latest fabric loader. Just out of curiosity

**Comment by lukasabbe** [comment]
You can download a 0.16.0 version here https://github.com/lukasabbe/Paste-book-text/actions/runs/11806829918/artifacts/2179050245
